// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * J​u​l​i​a​ ​S​a​n​f​r​a​n​c​i​s​c​o
		 */
		title: string
		/**
		 * C​h​a​s​e​ ​J​u​l​i​a​ ​a​n​d​ ​h​e​r​ ​a​c​c​o​m​p​l​i​c​e​s​ ​a​c​r​o​s​s​ ​d​i​f​f​e​r​e​n​t​ ​c​o​u​n​t​r​i​e​s​,​ ​u​n​r​a​v​e​l​i​n​g​ ​c​l​u​e​s​,​ ​s​o​l​v​i​n​g​ ​p​u​z​z​l​e​s​,​ ​a​n​d​ ​e​x​p​a​n​d​i​n​g​ ​y​o​u​r​ ​g​e​o​g​r​a​p​h​y​ ​k​n​o​w​l​e​d​g​e​ ​i​n​ ​t​h​i​s​ ​e​x​c​i​t​i​n​g​ ​d​e​t​e​c​t​i​v​e​ ​g​a​m​e​.
		 */
		introduction: string
		/**
		 * N​e​w​ ​g​a​m​e
		 */
		newGame: string
	}
	components: {
		/**
		 * L​o​a​d​i​n​g
		 */
		loading: string
		buttons: {
			/**
			 * C​o​n​t​i​n​u​e
			 */
			'continue': string
			/**
			 * Q​u​i​t
			 */
			quit: string
		}
	}
}

export type TranslationFunctions = {
	home: {
		/**
		 * Julia Sanfrancisco
		 */
		title: () => LocalizedString
		/**
		 * Chase Julia and her accomplices across different countries, unraveling clues, solving puzzles, and expanding your geography knowledge in this exciting detective game.
		 */
		introduction: () => LocalizedString
		/**
		 * New game
		 */
		newGame: () => LocalizedString
	}
	components: {
		/**
		 * Loading
		 */
		loading: () => LocalizedString
		buttons: {
			/**
			 * Continue
			 */
			'continue': () => LocalizedString
			/**
			 * Quit
			 */
			quit: () => LocalizedString
		}
	}
}

export type Formatters = {}
