// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * J​u​l​i​a​ ​S​a​n​f​r​a​n​c​i​s​c​o
		 */
		title: string
		/**
		 * C​h​a​s​e​ ​J​u​l​i​a​ ​a​n​d​ ​h​e​r​ ​a​c​c​o​m​p​l​i​c​e​s​ ​a​c​r​o​s​s​ ​d​i​f​f​e​r​e​n​t​ ​c​o​u​n​t​r​i​e​s​,​ ​u​n​r​a​v​e​l​i​n​g​ ​c​l​u​e​s​,​ ​s​o​l​v​i​n​g​ ​p​u​z​z​l​e​s​,​ ​a​n​d​ ​e​x​p​a​n​d​i​n​g​ ​y​o​u​r​ ​g​e​o​g​r​a​p​h​y​ ​k​n​o​w​l​e​d​g​e​ ​i​n​ ​t​h​i​s​ ​e​x​c​i​t​i​n​g​ ​d​e​t​e​c​t​i​v​e​ ​g​a​m​e​.
		 */
		introduction: string
		/**
		 * N​e​w​ ​g​a​m​e
		 */
		newGame: string
	}
	headquarters: {
		/**
		 * H​e​a​d​q​u​a​r​t​e​r​s
		 */
		title: string
		newsflash: {
			/**
			 * N​e​w​s​f​l​a​s​h
			 */
			title: string
			content: {
				/**
				 * N​a​t​i​o​n​a​l​ ​t​r​e​a​s​u​r​e​ ​s​t​o​l​e​n​ ​f​r​o​m​ ​{​c​i​t​y​}​.
				 * @param {string} city
				 */
				line1: RequiredParams<'city'>
				/**
				 * T​h​e​ ​t​r​e​a​s​u​r​e​ ​h​a​s​ ​b​e​e​n​ ​i​d​e​n​t​i​f​i​e​d​ ​a​s​ ​{​t​r​e​a​s​u​r​e​}​.
				 * @param {string} treasure
				 */
				line2: RequiredParams<'treasure'>
				/**
				 * {​s​e​x​}​ ​h​a​s​ ​b​e​e​n​ ​r​e​p​o​r​t​e​d​ ​a​t​ ​t​h​e​ ​s​c​e​n​e​ ​o​f​ ​t​h​e​ ​c​r​i​m​e​.
				 * @param {string} sex
				 */
				line3: RequiredParams<'sex'>
			}
		}
		assignment: {
			/**
			 * Y​o​u​r​ ​a​s​s​i​g​n​m​e​n​t
			 */
			title: string
			content: {
				/**
				 * T​r​a​c​k​ ​t​h​e​ ​t​h​i​e​f​ ​f​r​o​m​ ​{​c​i​t​y​}​ ​t​o​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​i​s​,​ ​f​e​m​a​l​e​:​ ​h​e​r​}​}​ ​h​i​d​e​o​u​t​ ​a​n​d​ ​a​r​r​e​s​t​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​i​m​,​ ​f​e​m​a​l​e​:​ ​h​e​r​}​}​.
				 * @param {string} city
				 * @param {string} sex
				 */
				line1: RequiredParams<'city' | `sex|{male:${string}, female:${string}}` | `sex|{male:${string}, female:${string}}`>
				/**
				 * Y​o​u​ ​m​u​s​t​ ​a​p​p​r​e​h​e​n​d​ ​t​h​e​ ​t​h​i​e​f​ ​b​y​ ​S​u​n​d​a​y​ ​5​p​m​.
				 */
				line2: string
				/**
				 * G​o​o​d​ ​l​u​c​k​,​ ​{​r​a​n​k​}​ ​{​n​a​m​e​}​.
				 * @param {string} name
				 * @param {string} rank
				 */
				line3: RequiredParams<'name' | 'rank'>
			}
		}
		id: {
			/**
			 * D​e​t​e​c​t​i​v​e​ ​a​t​ ​k​e​y​b​o​a​r​d​,​ ​p​l​e​a​s​e​ ​i​d​e​n​t​i​f​y​ ​y​o​u​r​s​e​l​f
			 */
			pending: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​i​d​e​n​t​i​f​i​e​d​ ​a​s​ ​{​n​a​m​e​}​.
			 * @param {string} name
			 */
			indentified: RequiredParams<'name'>
			/**
			 * Y​o​u​r​ ​c​u​r​r​e​n​t​ ​r​a​n​k​ ​i​s​ ​{​r​a​n​k​}​.
			 * @param {string} rank
			 */
			rank: RequiredParams<'rank'>
		}
	}
	game: {
		outcome: {
			/**
			 * M​e​s​s​a​g​e​ ​f​r​o​m​ ​I​n​t​e​r​p​o​l
			 */
			title: string
			win: {
				/**
				 * C​o​n​g​r​a​t​u​l​a​t​i​o​n​s​!
				 */
				line1: string
				/**
				 * Y​o​u​ ​c​a​u​g​h​t​ ​u​p​ ​w​i​t​h​ ​t​h​e​ ​s​u​s​p​e​c​t​.
				 */
				line2: string
				/**
				 * T​h​a​n​k​s​ ​t​o​ ​y​o​u​r​ ​h​e​l​p​,​ ​t​h​e​ ​{​c​i​t​y​}​ ​p​o​l​i​c​e​ ​h​a​v​e​ ​a​p​p​r​e​h​e​n​d​e​d​ ​{​s​u​s​p​e​c​t​}​.
				 * @param {string} city
				 * @param {string} suspect
				 */
				line3: RequiredParams<'city' | 'suspect'>
				/**
				 * W​e​ ​t​h​a​n​k​ ​y​o​u​ ​f​o​r​ ​y​o​u​r​ ​g​o​o​d​ ​w​o​r​k​ ​o​n​ ​t​h​i​s​ ​c​a​s​e​.​ ​Y​o​u​r​ ​s​u​c​c​e​s​s​ ​w​i​l​l​ ​b​e​ ​n​o​t​e​d​ ​o​n​ ​y​o​u​r​ ​r​e​c​o​r​d​.
				 */
				line4: string
				/**
				 * {​c​a​s​e​s​}​ ​m​o​r​e​ ​c​a​s​e​{​{​s​}​}​ ​u​n​t​i​l​ ​y​o​u​r​ ​n​e​x​t​ ​p​r​o​m​o​t​i​o​n​.
				 * @param {number} cases
				 */
				line5: RequiredParams<'cases'>
			}
			loose: {
				timedOut: {
					/**
					 * B​a​d​ ​n​e​w​s​.​.​.
					 */
					line1: string
					/**
					 * L​o​o​k​s​ ​l​i​k​e​ ​{​s​u​s​p​e​c​t​}​ ​s​l​i​p​p​e​d​ ​t​h​r​o​u​g​h​ ​y​o​u​r​ ​f​i​n​g​e​r​s​ ​b​e​c​a​u​s​e​ ​y​o​u​r​ ​i​n​v​e​s​t​i​g​a​t​i​o​n​ ​t​o​o​k​ ​t​o​o​ ​l​o​n​g​!
					 * @param {string} suspect
					 */
					line2: RequiredParams<'suspect'>
				}
				noWarrant: {
					/**
					 * Y​o​u​ ​c​a​u​g​h​t​ ​u​p​ ​w​i​t​h​ ​s​u​s​p​e​c​t​ ​{​s​u​s​p​e​c​t​}​!
					 * @param {string} suspect
					 */
					line1: RequiredParams<'suspect'>
					/**
					 * H​o​w​e​v​e​r​,​ ​w​i​t​h​o​u​t​ ​a​ ​w​a​r​r​a​n​t​ ​t​h​e​ ​{​c​i​t​y​}​ ​p​o​l​i​c​e​ ​c​a​n​n​o​t​ ​m​a​k​e​ ​a​n​ ​a​r​r​e​s​t​.
					 * @param {string} city
					 */
					line2: RequiredParams<'city'>
					/**
					 * I​t​ ​l​o​o​k​s​ ​l​i​k​e​ ​J​u​l​i​a​'​s​ ​g​a​n​g​ ​h​a​s​ ​g​o​t​t​e​n​ ​a​w​a​y​ ​w​i​t​h​ ​a​n​o​t​h​e​r​ ​c​a​p​e​r​.
					 */
					line3: string
				}
			}
			/**
			 * R​e​a​d​y​ ​f​o​r​ ​y​o​u​r​ ​n​e​x​t​ ​c​a​s​e​,​ ​{​r​a​n​k​}​ ​{​n​a​m​e​}​?
			 * @param {string} name
			 * @param {string} rank
			 */
			ready: RequiredParams<'name' | 'rank'>
		}
		actions: {
			/**
			 * Q​u​i​t
			 */
			quit: string
			/**
			 * W​a​l​k​ ​t​o
			 */
			walk: string
			/**
			 * F​l​y​ ​t​o
			 */
			fly: string
		}
	}
	clues: {
		introduction: {
			/**
			 * I​ ​s​a​w​ ​t​h​e​ ​p​e​r​s​o​n​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​a​n​d
			 */
			'0': string
			/**
			 * T​h​e​ ​p​e​r​s​o​n​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​w​a​s​ ​h​e​r​e​ ​a​n​d
			 */
			'1': string
			/**
			 * M​y​ ​s​o​u​r​c​e​s​ ​t​e​l​l​ ​m​e
			 */
			'2': string
			/**
			 * A​ ​r​e​l​i​a​b​l​e​ ​s​o​u​r​c​e​ ​t​o​l​d​ ​m​e
			 */
			'3': string
			/**
			 * S​o​u​r​c​e​s​ ​t​e​l​l​ ​m​e
			 */
			'4': string
			/**
			 * A​l​l​ ​I​ ​k​n​o​w​ ​i​s​ ​t​h​a​t
			 */
			'5': string
			/**
			 * A​ ​s​u​s​p​i​c​i​o​u​s​ ​p​e​r​s​o​n​ ​w​a​s​ ​h​e​r​e​ ​a​n​d
			 */
			'6': string
			/**
			 * I​ ​h​e​a​r​d
			 */
			'7': string
		}
		place: {
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​s​a​i​d​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​w​a​n​t​e​d​ ​t​o​ ​p​h​o​t​o​g​r​a​p​h
			 * @param {string} sex
			 */
			'0': RequiredParams<`sex|{male:${string}, female:${string}}` | `sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​a​s​k​e​d​ ​f​o​r​ ​a​ ​m​a​p​ ​o​f
			 * @param {string} sex
			 */
			'1': RequiredParams<`sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​p​l​a​n​n​e​d​ ​t​o​ ​v​i​s​i​t
			 * @param {string} sex
			 */
			'2': RequiredParams<`sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​m​e​n​t​i​o​n​e​d​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​w​a​n​t​e​d​ ​t​o​ ​s​e​e
			 * @param {string} sex
			 */
			'3': RequiredParams<`sex|{male:${string}, female:${string}}` | `sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​w​a​s​ ​c​o​n​s​i​d​e​r​i​n​g​ ​t​a​k​i​n​g​ ​a​ ​t​r​i​p​ ​t​o
			 * @param {string} sex
			 */
			'4': RequiredParams<`sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​h​a​d​ ​a​n​ ​u​r​g​e​ ​t​o​ ​v​i​s​i​t
			 * @param {string} sex
			 */
			'5': RequiredParams<`sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​s​a​i​d​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​w​a​n​t​e​d​ ​t​o​ ​e​x​p​l​o​r​e
			 * @param {string} sex
			 */
			'6': RequiredParams<`sex|{male:${string}, female:${string}}` | `sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​a​s​k​e​d​ ​a​b​o​u​t​ ​d​a​y​ ​t​o​u​r​s​ ​t​o
			 * @param {string} sex
			 */
			'7': RequiredParams<`sex|{male:${string}, female:${string}}`>
			/**
			 * {​s​e​x​|​{​m​a​l​e​:​ ​h​e​,​ ​f​e​m​a​l​e​:​ ​s​h​e​}​}​ ​w​a​n​t​e​d​ ​t​o​ ​k​n​o​w​ ​i​f​ ​t​h​e​r​e​ ​w​e​r​e​ ​a​n​y​ ​f​i​v​e​-​s​t​a​r​ ​h​o​t​e​l​s​ ​n​e​a​r
			 * @param {string} sex
			 */
			'8': RequiredParams<`sex|{male:${string}, female:${string}}`>
		}
		language: {
			/**
			 * h​a​d​ ​a​ ​{​l​a​n​g​u​a​g​e​}​ ​d​i​c​t​i​o​n​a​r​y​ ​i​n​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​i​s​,​ ​f​e​m​a​l​e​:​ ​h​e​r​}​}​ ​p​o​c​k​e​t
			 * @param {string} language
			 * @param {string} sex
			 */
			'0': RequiredParams<'language' | `sex|{male:${string}, female:${string}}`>
			/**
			 * w​a​s​ ​c​a​r​r​y​i​n​g​ ​a​ ​{​l​a​n​g​u​a​g​e​}​ ​p​h​r​a​s​e​ ​b​o​o​k
			 * @param {string} language
			 */
			'1': RequiredParams<'language'>
		}
		currency: {
			/**
			 * c​h​a​n​g​e​d​ ​{​s​e​x​|​{​m​a​l​e​:​ ​h​i​s​,​ ​f​e​m​a​l​e​:​ ​h​e​r​}​}​ ​m​o​n​e​y​ ​t​o​ ​{​c​u​r​r​e​n​c​y​}
			 * @param {string} currency
			 * @param {string} sex
			 */
			'0': RequiredParams<'currency' | `sex|{male:${string}, female:${string}}`>
			/**
			 * a​s​k​e​d​ ​a​b​o​u​t​ ​t​h​e​ ​e​x​c​h​a​n​g​e​ ​r​a​t​e​ ​f​o​r​ ​{​c​u​r​r​e​n​c​y​}
			 * @param {string} currency
			 */
			'1': RequiredParams<'currency'>
			/**
			 * w​a​n​t​e​d​ ​t​o​ ​k​n​o​w​ ​h​o​w​ ​m​u​c​h​ ​{​c​u​r​r​e​n​c​y​}​ ​w​e​r​e​ ​w​o​r​t​h
			 * @param {string} currency
			 */
			'2': RequiredParams<'currency'>
		}
		object: {
			/**
			 * w​a​s​ ​c​a​r​r​y​i​n​g​ ​a
			 */
			'0': string
			/**
			 * w​a​n​t​e​d​ ​t​o​ ​g​e​t
			 */
			'1': string
			/**
			 * w​a​n​t​e​d​ ​t​o​ ​s​e​l​l
			 */
			'2': string
			/**
			 * a​s​k​e​d​ ​w​h​e​r​e​ ​t​o​ ​f​i​n​d
			 */
			'3': string
			/**
			 * w​a​s​ ​l​o​o​k​i​n​g​ ​f​o​r
			 */
			'4': string
		}
		topic: {
			/**
			 * w​a​s​ ​r​e​s​e​a​r​c​h​i​n​g
			 */
			'0': string
			/**
			 * w​a​n​t​e​d​ ​t​o​ ​s​t​u​d​y
			 */
			'1': string
			/**
			 * w​a​s​ ​i​n​t​e​r​e​s​t​e​d​ ​i​n
			 */
			'2': string
			/**
			 * a​s​k​e​d​ ​a​b​o​u​t
			 */
			'3': string
		}
		plane: {
			/**
			 * l​e​f​t​ ​i​n​ ​a​ ​p​l​a​n​e​ ​w​i​t​h​ ​a​ ​{​f​l​a​g​}​ ​o​n​ ​i​t​s​ ​w​i​n​g
			 * @param {string} flag
			 */
			'0': RequiredParams<'flag'>
			/**
			 * w​a​s​ ​i​n​ ​a​ ​r​u​s​h​ ​t​o​ ​c​a​t​c​h​ ​a​ ​p​l​a​n​e​ ​w​i​t​h​ ​a​ ​{​f​l​a​g​}​ ​o​n​ ​i​t​s​ ​w​i​n​g
			 * @param {string} flag
			 */
			'1': RequiredParams<'flag'>
			/**
			 * f​l​e​w​ ​a​w​a​y​ ​o​n​ ​a​ ​p​l​a​n​e​ ​w​i​t​h​ ​a​ ​{​f​l​a​g​}​ ​o​n​ ​i​t​s​ ​t​a​i​l
			 * @param {string} flag
			 */
			'2': RequiredParams<'flag'>
		}
		ship: {
			/**
			 * s​a​i​l​e​d​ ​a​w​a​y​ ​o​n​ ​a​ ​s​h​i​p​ ​f​l​y​i​n​g​ ​a​ ​{​f​l​a​g​}​ ​f​l​a​g
			 * @param {string} flag
			 */
			'0': RequiredParams<'flag'>
			/**
			 * l​e​f​t​ ​o​n​ ​a​ ​s​h​i​p​ ​w​i​t​h​ ​a​ ​{​f​l​a​g​}​ ​f​l​a​g
			 * @param {string} flag
			 */
			'1': RequiredParams<'flag'>
		}
		finalRound: {
			/**
			 * T​h​e​ ​w​o​r​d​ ​i​s​ ​o​u​t​,​ ​y​o​u​'​r​e​ ​g​e​t​t​i​n​g​ ​t​o​o​ ​c​l​o​s​e​ ​g​u​m​s​h​o​e​.​.​.
			 */
			'0': string
			/**
			 * R​u​m​o​r​ ​h​a​s​ ​i​t​ ​t​h​a​t​ ​t​h​e​ ​g​a​n​g​ ​i​s​ ​i​n​ ​t​o​w​n​ ​s​o​m​e​w​h​e​r​e​.
			 */
			'1': string
			/**
			 * A​l​l​ ​I​ ​k​n​o​w​ ​i​s​ ​t​h​a​t​ ​s​o​m​e​t​h​i​n​g​ ​s​u​s​p​i​c​i​o​u​s​ ​i​s​ ​h​a​p​p​e​n​i​n​g​ ​i​n​ ​t​o​w​n​.
			 */
			'2': string
			/**
			 * T​h​e​ ​o​n​l​y​ ​t​h​i​n​g​ ​I​ ​c​a​n​ ​t​e​l​l​ ​y​o​u​ ​i​s​ ​t​o​ ​w​a​t​c​h​ ​y​o​u​r​ ​s​t​e​p​.
			 */
			'3': string
		}
	}
	scenes: {
		places: {
			/**
			 * A​i​r​p​o​r​t
			 */
			'0': string
			/**
			 * B​a​n​k
			 */
			'1': string
			/**
			 * F​o​r​e​i​g​n​ ​m​i​n​i​s​t​r​y
			 */
			'2': string
			/**
			 * H​a​r​b​o​r
			 */
			'3': string
			/**
			 * H​o​t​e​l
			 */
			'4': string
			/**
			 * L​i​b​r​a​r​y
			 */
			'5': string
			/**
			 * M​a​r​k​e​t
			 */
			'6': string
			/**
			 * M​u​s​e​u​m
			 */
			'7': string
			/**
			 * P​a​l​a​c​e
			 */
			'8': string
			/**
			 * R​i​v​e​r​f​r​o​n​t
			 */
			'9': string
			/**
			 * S​p​o​r​t​ ​c​l​u​b
			 */
			'10': string
			/**
			 * S​t​o​c​k​ ​e​x​c​h​a​n​g​e
			 */
			'11': string
		}
		witnesses: {
			/**
			 * B​a​g​g​a​g​e​ ​c​l​e​r​k
			 */
			'0': string
			/**
			 * F​l​i​g​h​t​ ​a​t​t​e​n​d​a​n​t
			 */
			'1': string
			/**
			 * P​i​l​o​t
			 */
			'2': string
			/**
			 * B​a​n​k​ ​g​u​a​r​d
			 */
			'3': string
			/**
			 * T​e​l​l​e​r
			 */
			'4': string
			/**
			 * V​i​c​e​ ​p​r​e​s​i​d​e​n​t
			 */
			'5': string
			/**
			 * A​m​b​a​s​s​a​d​o​r
			 */
			'6': string
			/**
			 * A​t​t​a​c​h​e
			 */
			'7': string
			/**
			 * U​n​d​e​r​ ​s​e​c​r​e​t​a​r​y
			 */
			'8': string
			/**
			 * C​u​s​t​o​m​s​ ​o​f​f​i​c​e​r
			 */
			'9': string
			/**
			 * H​a​r​b​o​r​ ​m​a​s​t​e​r
			 */
			'10': string
			/**
			 * S​a​i​l​o​r
			 */
			'11': string
			/**
			 * B​e​l​l​h​o​p
			 */
			'12': string
			/**
			 * H​o​u​s​e​ ​d​e​t​e​c​t​i​v​e
			 */
			'13': string
			/**
			 * H​o​t​e​l​ ​m​a​n​a​g​e​r
			 */
			'14': string
			/**
			 * A​r​c​h​i​v​i​s​t
			 */
			'15': string
			/**
			 * C​i​r​c​u​l​a​t​i​o​n​ ​c​l​e​r​k
			 */
			'16': string
			/**
			 * R​e​f​e​r​e​n​c​e​ ​l​i​b​r​a​r​i​a​n
			 */
			'17': string
			/**
			 * H​a​w​k​e​r
			 */
			'18': string
			/**
			 * S​t​r​e​e​t​ ​m​e​r​c​h​a​n​t
			 */
			'19': string
			/**
			 * U​r​c​h​i​n
			 */
			'20': string
			/**
			 * C​u​r​a​t​o​r
			 */
			'21': string
			/**
			 * D​o​c​e​n​t
			 */
			'22': string
			/**
			 * M​u​s​e​u​m​ ​g​u​a​r​d
			 */
			'23': string
			/**
			 * P​a​l​a​c​e​ ​g​u​a​r​d
			 */
			'24': string
			/**
			 * P​r​i​v​y​ ​c​o​u​n​c​i​l​l​o​r
			 */
			'25': string
			/**
			 * S​o​l​d​i​e​r
			 */
			'26': string
			/**
			 * S​a​i​l​o​r​'​s​ ​p​a​r​r​o​t
			 */
			'27': string
			/**
			 * S​t​e​v​e​d​o​r​e
			 */
			'28': string
			/**
			 * T​u​g​b​o​a​t​ ​c​a​p​t​a​i​n
			 */
			'29': string
			/**
			 * B​a​r​t​e​n​d​e​r
			 */
			'30': string
			/**
			 * T​e​n​n​i​s​ ​p​r​o
			 */
			'31': string
			/**
			 * W​a​i​t​e​r
			 */
			'32': string
			/**
			 * A​n​a​l​y​s​t
			 */
			'33': string
			/**
			 * M​e​s​s​e​n​g​e​r
			 */
			'34': string
			/**
			 * T​r​a​d​e​r
			 */
			'35': string
		}
	}
	player: {
		ranks: {
			/**
			 * R​o​o​k​i​e
			 */
			'0': string
			/**
			 * S​l​e​u​t​h
			 */
			'1': string
			/**
			 * P​r​i​v​a​t​e​ ​e​y​e
			 */
			'2': string
			/**
			 * I​n​v​e​s​t​i​g​a​t​o​r
			 */
			'3': string
			/**
			 * A​c​e​ ​d​e​t​e​c​t​i​v​e
			 */
			'4': string
			/**
			 * S​u​p​e​r​ ​s​l​e​u​t​h
			 */
			'5': string
		}
	}
	components: {
		/**
		 * L​o​a​d​i​n​g
		 */
		loading: string
		buttons: {
			/**
			 * C​o​n​t​i​n​u​e
			 */
			'continue': string
			/**
			 * Q​u​i​t
			 */
			quit: string
		}
	}
}

export type TranslationFunctions = {
	home: {
		/**
		 * Julia Sanfrancisco
		 */
		title: () => LocalizedString
		/**
		 * Chase Julia and her accomplices across different countries, unraveling clues, solving puzzles, and expanding your geography knowledge in this exciting detective game.
		 */
		introduction: () => LocalizedString
		/**
		 * New game
		 */
		newGame: () => LocalizedString
	}
	headquarters: {
		/**
		 * Headquarters
		 */
		title: () => LocalizedString
		newsflash: {
			/**
			 * Newsflash
			 */
			title: () => LocalizedString
			content: {
				/**
				 * National treasure stolen from {city}.
				 */
				line1: (arg: { city: string }) => LocalizedString
				/**
				 * The treasure has been identified as {treasure}.
				 */
				line2: (arg: { treasure: string }) => LocalizedString
				/**
				 * {sex} has been reported at the scene of the crime.
				 */
				line3: (arg: { sex: string }) => LocalizedString
			}
		}
		assignment: {
			/**
			 * Your assignment
			 */
			title: () => LocalizedString
			content: {
				/**
				 * Track the thief from {city} to {sex|{male: his, female: her}} hideout and arrest {sex|{male: him, female: her}}.
				 */
				line1: (arg: { city: string, sex: string }) => LocalizedString
				/**
				 * You must apprehend the thief by Sunday 5pm.
				 */
				line2: () => LocalizedString
				/**
				 * Good luck, {rank} {name}.
				 */
				line3: (arg: { name: string, rank: string }) => LocalizedString
			}
		}
		id: {
			/**
			 * Detective at keyboard, please identify yourself
			 */
			pending: () => LocalizedString
			/**
			 * You have been identified as {name}.
			 */
			indentified: (arg: { name: string }) => LocalizedString
			/**
			 * Your current rank is {rank}.
			 */
			rank: (arg: { rank: string }) => LocalizedString
		}
	}
	game: {
		outcome: {
			/**
			 * Message from Interpol
			 */
			title: () => LocalizedString
			win: {
				/**
				 * Congratulations!
				 */
				line1: () => LocalizedString
				/**
				 * You caught up with the suspect.
				 */
				line2: () => LocalizedString
				/**
				 * Thanks to your help, the {city} police have apprehended {suspect}.
				 */
				line3: (arg: { city: string, suspect: string }) => LocalizedString
				/**
				 * We thank you for your good work on this case. Your success will be noted on your record.
				 */
				line4: () => LocalizedString
				/**
				 * {cases} more case{{s}} until your next promotion.
				 */
				line5: (arg: { cases: number }) => LocalizedString
			}
			loose: {
				timedOut: {
					/**
					 * Bad news...
					 */
					line1: () => LocalizedString
					/**
					 * Looks like {suspect} slipped through your fingers because your investigation took too long!
					 */
					line2: (arg: { suspect: string }) => LocalizedString
				}
				noWarrant: {
					/**
					 * You caught up with suspect {suspect}!
					 */
					line1: (arg: { suspect: string }) => LocalizedString
					/**
					 * However, without a warrant the {city} police cannot make an arrest.
					 */
					line2: (arg: { city: string }) => LocalizedString
					/**
					 * It looks like Julia's gang has gotten away with another caper.
					 */
					line3: () => LocalizedString
				}
			}
			/**
			 * Ready for your next case, {rank} {name}?
			 */
			ready: (arg: { name: string, rank: string }) => LocalizedString
		}
		actions: {
			/**
			 * Quit
			 */
			quit: () => LocalizedString
			/**
			 * Walk to
			 */
			walk: () => LocalizedString
			/**
			 * Fly to
			 */
			fly: () => LocalizedString
		}
	}
	clues: {
		introduction: {
			/**
			 * I saw the person you're looking for and
			 */
			'0': () => LocalizedString
			/**
			 * The person you are looking for was here and
			 */
			'1': () => LocalizedString
			/**
			 * My sources tell me
			 */
			'2': () => LocalizedString
			/**
			 * A reliable source told me
			 */
			'3': () => LocalizedString
			/**
			 * Sources tell me
			 */
			'4': () => LocalizedString
			/**
			 * All I know is that
			 */
			'5': () => LocalizedString
			/**
			 * A suspicious person was here and
			 */
			'6': () => LocalizedString
			/**
			 * I heard
			 */
			'7': () => LocalizedString
		}
		place: {
			/**
			 * {sex|{male: he, female: she}} said {sex|{male: he, female: she}} wanted to photograph
			 */
			'0': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} asked for a map of
			 */
			'1': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} planned to visit
			 */
			'2': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} mentioned {sex|{male: he, female: she}} wanted to see
			 */
			'3': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} was considering taking a trip to
			 */
			'4': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} had an urge to visit
			 */
			'5': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} said {sex|{male: he, female: she}} wanted to explore
			 */
			'6': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} asked about day tours to
			 */
			'7': (arg: { sex: string }) => LocalizedString
			/**
			 * {sex|{male: he, female: she}} wanted to know if there were any five-star hotels near
			 */
			'8': (arg: { sex: string }) => LocalizedString
		}
		language: {
			/**
			 * had a {language} dictionary in {sex|{male: his, female: her}} pocket
			 */
			'0': (arg: { language: string, sex: string }) => LocalizedString
			/**
			 * was carrying a {language} phrase book
			 */
			'1': (arg: { language: string }) => LocalizedString
		}
		currency: {
			/**
			 * changed {sex|{male: his, female: her}} money to {currency}
			 */
			'0': (arg: { currency: string, sex: string }) => LocalizedString
			/**
			 * asked about the exchange rate for {currency}
			 */
			'1': (arg: { currency: string }) => LocalizedString
			/**
			 * wanted to know how much {currency} were worth
			 */
			'2': (arg: { currency: string }) => LocalizedString
		}
		object: {
			/**
			 * was carrying a
			 */
			'0': () => LocalizedString
			/**
			 * wanted to get
			 */
			'1': () => LocalizedString
			/**
			 * wanted to sell
			 */
			'2': () => LocalizedString
			/**
			 * asked where to find
			 */
			'3': () => LocalizedString
			/**
			 * was looking for
			 */
			'4': () => LocalizedString
		}
		topic: {
			/**
			 * was researching
			 */
			'0': () => LocalizedString
			/**
			 * wanted to study
			 */
			'1': () => LocalizedString
			/**
			 * was interested in
			 */
			'2': () => LocalizedString
			/**
			 * asked about
			 */
			'3': () => LocalizedString
		}
		plane: {
			/**
			 * left in a plane with a {flag} on its wing
			 */
			'0': (arg: { flag: string }) => LocalizedString
			/**
			 * was in a rush to catch a plane with a {flag} on its wing
			 */
			'1': (arg: { flag: string }) => LocalizedString
			/**
			 * flew away on a plane with a {flag} on its tail
			 */
			'2': (arg: { flag: string }) => LocalizedString
		}
		ship: {
			/**
			 * sailed away on a ship flying a {flag} flag
			 */
			'0': (arg: { flag: string }) => LocalizedString
			/**
			 * left on a ship with a {flag} flag
			 */
			'1': (arg: { flag: string }) => LocalizedString
		}
		finalRound: {
			/**
			 * The word is out, you're getting too close gumshoe...
			 */
			'0': () => LocalizedString
			/**
			 * Rumor has it that the gang is in town somewhere.
			 */
			'1': () => LocalizedString
			/**
			 * All I know is that something suspicious is happening in town.
			 */
			'2': () => LocalizedString
			/**
			 * The only thing I can tell you is to watch your step.
			 */
			'3': () => LocalizedString
		}
	}
	scenes: {
		places: {
			/**
			 * Airport
			 */
			'0': () => LocalizedString
			/**
			 * Bank
			 */
			'1': () => LocalizedString
			/**
			 * Foreign ministry
			 */
			'2': () => LocalizedString
			/**
			 * Harbor
			 */
			'3': () => LocalizedString
			/**
			 * Hotel
			 */
			'4': () => LocalizedString
			/**
			 * Library
			 */
			'5': () => LocalizedString
			/**
			 * Market
			 */
			'6': () => LocalizedString
			/**
			 * Museum
			 */
			'7': () => LocalizedString
			/**
			 * Palace
			 */
			'8': () => LocalizedString
			/**
			 * Riverfront
			 */
			'9': () => LocalizedString
			/**
			 * Sport club
			 */
			'10': () => LocalizedString
			/**
			 * Stock exchange
			 */
			'11': () => LocalizedString
		}
		witnesses: {
			/**
			 * Baggage clerk
			 */
			'0': () => LocalizedString
			/**
			 * Flight attendant
			 */
			'1': () => LocalizedString
			/**
			 * Pilot
			 */
			'2': () => LocalizedString
			/**
			 * Bank guard
			 */
			'3': () => LocalizedString
			/**
			 * Teller
			 */
			'4': () => LocalizedString
			/**
			 * Vice president
			 */
			'5': () => LocalizedString
			/**
			 * Ambassador
			 */
			'6': () => LocalizedString
			/**
			 * Attache
			 */
			'7': () => LocalizedString
			/**
			 * Under secretary
			 */
			'8': () => LocalizedString
			/**
			 * Customs officer
			 */
			'9': () => LocalizedString
			/**
			 * Harbor master
			 */
			'10': () => LocalizedString
			/**
			 * Sailor
			 */
			'11': () => LocalizedString
			/**
			 * Bellhop
			 */
			'12': () => LocalizedString
			/**
			 * House detective
			 */
			'13': () => LocalizedString
			/**
			 * Hotel manager
			 */
			'14': () => LocalizedString
			/**
			 * Archivist
			 */
			'15': () => LocalizedString
			/**
			 * Circulation clerk
			 */
			'16': () => LocalizedString
			/**
			 * Reference librarian
			 */
			'17': () => LocalizedString
			/**
			 * Hawker
			 */
			'18': () => LocalizedString
			/**
			 * Street merchant
			 */
			'19': () => LocalizedString
			/**
			 * Urchin
			 */
			'20': () => LocalizedString
			/**
			 * Curator
			 */
			'21': () => LocalizedString
			/**
			 * Docent
			 */
			'22': () => LocalizedString
			/**
			 * Museum guard
			 */
			'23': () => LocalizedString
			/**
			 * Palace guard
			 */
			'24': () => LocalizedString
			/**
			 * Privy councillor
			 */
			'25': () => LocalizedString
			/**
			 * Soldier
			 */
			'26': () => LocalizedString
			/**
			 * Sailor's parrot
			 */
			'27': () => LocalizedString
			/**
			 * Stevedore
			 */
			'28': () => LocalizedString
			/**
			 * Tugboat captain
			 */
			'29': () => LocalizedString
			/**
			 * Bartender
			 */
			'30': () => LocalizedString
			/**
			 * Tennis pro
			 */
			'31': () => LocalizedString
			/**
			 * Waiter
			 */
			'32': () => LocalizedString
			/**
			 * Analyst
			 */
			'33': () => LocalizedString
			/**
			 * Messenger
			 */
			'34': () => LocalizedString
			/**
			 * Trader
			 */
			'35': () => LocalizedString
		}
	}
	player: {
		ranks: {
			/**
			 * Rookie
			 */
			'0': () => LocalizedString
			/**
			 * Sleuth
			 */
			'1': () => LocalizedString
			/**
			 * Private eye
			 */
			'2': () => LocalizedString
			/**
			 * Investigator
			 */
			'3': () => LocalizedString
			/**
			 * Ace detective
			 */
			'4': () => LocalizedString
			/**
			 * Super sleuth
			 */
			'5': () => LocalizedString
		}
	}
	components: {
		/**
		 * Loading
		 */
		loading: () => LocalizedString
		buttons: {
			/**
			 * Continue
			 */
			'continue': () => LocalizedString
			/**
			 * Quit
			 */
			quit: () => LocalizedString
		}
	}
}

export type Formatters = {}
